### ISSUE TITLE
no graceful shutdown of tgtd

### ISSUE THREAD

**Issue by rdxmb** [kvaps/kube-iscsi-lb#1]
When running `tgtd -f`, stopping the docker container causes a rude kill of the process instead of a graceful shutdown.

This is because `tgtd` does not listen to SIGTERM or SIGINT - so docker is sending a SIGKILL to the process.

See https://github.com/fujita/tgt/blob/master/scripts/tgtd.service for details

**Comment by rdxmb** [comment]
When will this be built and pushed to docker hub?

At the moment, the yaml does not work, for the command is not available in the official image.

**Comment by kvaps** [comment]
True, there was some problem in docker hub, I've recreated repo
