### ISSUE TITLE
iscisd not starting

### ISSUE THREAD

**Issue by rdxmb** [kvaps/kube-iscsi-lb#3]
```
root@ubuntu:/home/marc# docker run --net=host --privileged -v /lib/modules:/lib/modules -v /dev:/dev -v /run:/run kvaps/iscsi iscsid -f
iscsid: Can not bind IPC socket

```

Same problem when starting via kubectl:

```
k3.mbr.intern:/mnt/glusterfs/k8-orchestration/iscsi-provisioning$ kubectl logs iscsi-xqrxp iscsid
iscsid: Can not bind IPC socket

```

What's the problem here?

**Comment by kvaps** [comment]
This is happening if you already have wokring `iscsid` in your system, try check `ps aux | grep iscsid`, before run

**Comment by rdxmb** [comment]
yes, just checked this out. 

this seems to be a problem when my host already uses open-iscsi with https://github.com/kubernetes/examples/tree/master/staging/volumes/iscsi

Is the iscsi-pod necessary for provisioning the targets and pv(c)s?

I want to have a setup like

`SAN --- mount iscsi one target ---> Pod ---- iscsi several targets (with tgtd) ----> ....`

**Comment by kvaps** [comment]
No problem, you can use your own, just remove **iscsid** container from this manifest:
https://github.com/kvaps/kube-iscsi-loop/blob/master/iscsi/iscsi.yaml#L45

**Comment by kvaps** [comment]
If you want just provisioner, you can use only provisioner, but you should understand, that's right now it is working only with localy hosted files, and creates exports only for local use.
But you can simple adapt my script for remote provisioning if you want, it should be very easy.

**Comment by rdxmb** [comment]
ok, thanks, that was really helpful for now.

So I will first play with the sharedfs-provisioner and -publisher and then will try to adapt it for my iscsi-mounted container.

Seems like I will have to put the provisioner, publisher and and tgtd into one container, to have the "main-iscsi" mounted only once into that.

...
